# Generated by Django 2.2.5 on 2019-11-05 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Recepi_Ingredient',
            fields=[
                ('recepi_ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('recepi_ingredient_name', models.CharField(max_length=45)),
                ('recepi_ingredient_type', models.CharField(max_length=45)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='recipeinfo.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='recipeinfo.Recipe')),
            ],
        ),
    ]
