# Generated by Django 2.2.5 on 2019-12-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('beverage_id', models.AutoField(primary_key=True, serialize=False)),
                ('beverage_name', models.CharField(max_length=45)),
                ('beverage_type', models.CharField(default='', max_length=45)),
            ],
            options={
                'ordering': ['beverage_type'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=45, unique=True)),
                ('is_vegetarian', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='recipeinfo.Category')),
            ],
            options={
                'ordering': ['ingredient_name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=45)),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='recipeinfo.Beverage')),
            ],
            options={
                'ordering': ['recipe_name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe_Type',
            fields=[
                ('recipe_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_type_name', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['recipe_type_name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe_Ingredient',
            fields=[
                ('recipe_ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_ingredient_name', models.CharField(max_length=45)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='recipeinfo.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='recipeinfo.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='recipeinfo.Recipe_Type'),
        ),
        migrations.CreateModel(
            name='Beverage_Ingredient',
            fields=[
                ('beverage_ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('beverage_ingredient_name', models.CharField(max_length=45)),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beverage_ingredients', to='recipeinfo.Beverage')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beverage_ingredients', to='recipeinfo.Ingredient')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('recipe_type', 'recipe_name')},
        ),
    ]
