# Generated by Django 2.2.5 on 2019-12-04 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beverage_ingredient',
            name='beverage_ingredient_name',
        ),
        migrations.RemoveField(
            model_name='recipe_ingredient',
            name='recipe_ingredient_name',
        ),
    ]
