# Generated by Django 2.2.5 on 2019-11-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepi_ingredient',
            name='recepi_ingredient_name',
        ),
        migrations.RemoveField(
            model_name='recepi_ingredient',
            name='recepi_ingredient_type',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(default='Temporary', max_length=45),
        ),
    ]
