# Generated by Django 2.2.5 on 2019-11-07 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeinfo', '0002_auto_20191105_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe_Ingredient',
            fields=[
                ('recipe_ingredient_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['ingredient'],
            },
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['ingredient_name']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['recipe_type']},
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('recipe_type', 'recipe_name')},
        ),
        migrations.DeleteModel(
            name='Recepi_Ingredient',
        ),
        migrations.AddField(
            model_name='recipe_ingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='recipeinfo.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe_ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='recipeinfo.Recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='recipe_ingredient',
            unique_together={('ingredient', 'recipe')},
        ),
    ]
