# Generated by Django 2.2.5 on 2019-12-11 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeinfo', '0002_auto_20191204_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('dessert_id', models.AutoField(primary_key=True, serialize=False)),
                ('dessert_name', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['dessert_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='beverage',
            options={'ordering': ['beverage_name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name']},
        ),
        migrations.CreateModel(
            name='Dessert_Ingredient',
            fields=[
                ('dessert_ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('dessert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dessert_ingredients', to='recipeinfo.Dessert')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dessert_ingredients', to='recipeinfo.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='dessert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='recipeinfo.Dessert'),
        ),
    ]
